name: deploy-container

on: 
  push:
    branches:
      - main
    paths:
      - 'products/**'

defaults:
  run:
    working-directory: products

jobs:
  build: 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run webpack

      - uses: shinyinc/action-aws-cli@v1.2
      - run: aws s3 aync dist s3://${{ secrets.AWS_S3_BUCKET_NAME }}/apps/products
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}