name: deploy-products-app

on: 
  push:
    branches:
      - main
    paths:
      - 'products/**'

defaults:
  run:
    working-directory: products

jobs:
  build: 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: yarn install
      - run: yarn webpack

      - uses: shinyinc/action-aws-cli@v1.2
      - run: aws s3 sync ./build s3://${{ secrets.AWS_S3_BUCKET_NAME }}/apps/products --request-payer requester
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "ap-southeast-1"